"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import AppShell from "@/app/components/app-shell";
import { ActionForm, Field, requestJson, compressPhoto } from "@/app/components/forms";
import type { GoogleUser } from "@/app/lib/google-auth";
import { type PortalRole, portalDefinitions } from "@/app/lib/portals";
const actions:Record<string,string[]>={farmer:["Complete shearing with photo"],buyer:["Wool received"],laboratory:["Sample received"],transporter:["Pickup recorded","Delivery recorded"],warehouse:["Storage intake","Storage released"],processor:["Scouring completed","Carding completed","Spinning completed","Weaving completed","Dyeing completed"],brand:["Finished product recorded"]};
type Batch={id:string;breed:string;weight:number};type Lot={id:string;name:string;kind:string;weightKg:number;parentLotId:string|null};
export default function PortalActions({role,actualRole,user}:{role:PortalRole;actualRole:string;user:GoogleUser}){
 const [batches,setBatches]=useState<Batch[]>([]),[batchId,setBatchId]=useState(""),[lots,setLots]=useState<Lot[]>([]),[error,setError]=useState("");
 useEffect(()=>{requestJson<{batches:Batch[]}>("/api/batches").then(d=>setBatches(d.batches)).catch(e=>setError(e.message));},[]);
 async function loadLots(id:string){setBatchId(id);setLots([]);if(!id)return;try{setLots((await requestJson<{lots:Lot[]}>("/api/lots?batchId="+id)).lots);}catch(e){setError((e as Error).message);}}
 const select=<label>Assigned batch<select name="batchId" required value={batchId} onChange={e=>loadLots(e.target.value)}><option value="">Select a batch</option>{batches.map(b=><option key={b.id} value={b.id}>{b.breed} · {b.id.slice(0,15)}… · {b.weight} kg</option>)}</select></label>;
 return <AppShell user={user}><header className="wt-page-head"><div><p className="wt-eyebrow">YOUR STAGE IN THE JOURNEY</p><h1>{portalDefinitions[role].name}</h1><p>{portalDefinitions[role].description}</p></div><Link className="wt-outline" href="/workspace/my-wool">Manage batches →</Link></header>{error&&<p role="alert" className="wt-error">{error}</p>}
 {actualRole!==role?<section className="wt-card"><h2>This is the {role} workspace.</h2><p>Your selected role is {actualRole}. Change your profile if this is the role you perform. Partner accounts still need the owner’s batch invitation.</p><Link className="wt-button" href="/profile">Update my profile</Link></section>:<div className="wt-two-columns"><section className="wt-card"><h2>{role==="farmer"?"Complete the shearing record":"Record a stage update"}</h2><p>{role==="farmer"?"Add the actual completion date, final wool weight and a photo.":"Choose a batch assigned to your Google email. Your update becomes public on its QR passport."}</p><ActionForm submit="Save to wool journey" onSubmit={async data=>{
 const payload:Record<string,unknown>={...Object.fromEntries(data),portalRole:role};
 if(role==="farmer"){const file=data.get("photo");if(!(file instanceof File))throw new Error("Choose a shearing photo.");payload.evidenceImageData=await compressPhoto(file);}delete payload.photo;
 await requestJson("/api/batches/events",{method:"POST",body:JSON.stringify(payload)});
 }}>{select}<label>Stage<select name="title">{actions[role].map(a=><option key={a}>{a}</option>)}</select></label><Field name="location" label="Farm, facility or handover location"/>
 {role==="farmer"&&<><Field name="shearedAt" label="Shearing completion date" type="date" max={new Date().toISOString().slice(0,10)}/><Field name="finalWeightKg" label="Final wool weight (kg)" type="number" min=".01" max="100000" step=".01"/><label>Shearing photo<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required/></label><p className="wt-help">Up to 15 MB. Compressed on your device before storage. The photo appears on the public passport.</p></>}
 <label>Stage details (optional)<textarea name="notes" rows={4} maxLength={500} placeholder="Weights, conditions, processing details or a report reference. Do not include private contact details."/></label><label className="wt-check"><input type="checkbox" required/> These details are accurate to the best of my knowledge and may be shown publicly.</label></ActionForm></section>
 <section className="wt-card wt-soft"><h2>Continue the work</h2>{role==="farmer"&&<><Link className="wt-quick-link" href="/workspace/my-wool">Register wool, list a batch or invite partners →</Link><Link className="wt-quick-link" href="/workspace/reverse-bidding">Compare offers and confirm payment →</Link></>}{role==="buyer"&&<Link className="wt-quick-link" href="/workspace/woolkart">Browse wool and place an offer →</Link>}{role==="laboratory"&&<Link className="wt-quick-link" href="/workspace/quality">Record fibre measurements →</Link>}
 {["processor","brand"].includes(role)&&<><h3>Create a traceable output lot</h3><p>Allocate output weight from the source batch or an existing parent lot. The total cannot exceed the parent’s weight.</p><ActionForm submit="Create lot & QR passport" onSubmit={async data=>{await requestJson("/api/lots",{method:"POST",body:JSON.stringify({...Object.fromEntries(data),batchId})});await loadLots(batchId);}}><p>{batchId?"Selected batch: "+batchId:"Select a batch in the stage form first."}</p><label>Parent<select name="parentLotId"><option value="">Source wool batch</option>{lots.map(l=><option value={l.id} key={l.id}>{l.name} · {l.weightKg} kg</option>)}</select></label><Field name="name" label="Lot or product name"/><label>Output type<select name="kind">{["clean_wool","yarn","fabric","product"].map(k=><option key={k} value={k}>{k.replaceAll("_"," ")}</option>)}</select></label><Field name="weightKg" label="Output weight (kg)" type="number" min=".01" max="100000" step=".01"/></ActionForm>{lots.map(l=><Link className="wt-quick-link" key={l.id} href={"/lot/"+l.id}>{l.name} · {l.weightKg} kg · Open QR →</Link>)}</>}
 {batchId&&<Link className="wt-quick-link" href={"/batch/"+batchId}>Open this batch’s public journey →</Link>}<p className="wt-help">These are participant-submitted records, not independent certification. Each update is linked to its account and previous event.</p></section></div>}</AppShell>;
}
