"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import AppShell from "@/app/components/app-shell";
import { ActionForm, Field, SelectField, NotesField, PhotoField, FormSection, requestJson, compressPhoto } from "@/app/components/forms";
import { indiaToday } from "@/app/lib/dates";
import type { GoogleUser } from "@/app/lib/google-auth";
import { type PortalRole, portalDefinitions } from "@/app/lib/portals";
const actions:Record<string,string[]>={farmer:["Complete shearing with photo"],buyer:["Wool received"],laboratory:["Sample received"],transporter:["Pickup recorded","Delivery recorded"],warehouse:["Storage intake","Storage released"],processor:["Scouring completed","Carding completed","Spinning completed","Weaving completed","Dyeing completed"],brand:["Finished product recorded"]};
type Batch={id:string;breed:string;weight:number};type Lot={id:string;name:string;kind:string;weightKg:number;parentLotId:string|null};
export default function PortalActions({role,actualRole,user,initialBatchId}:{role:PortalRole;actualRole:string;user:GoogleUser;initialBatchId?:string}){
 const [batches,setBatches]=useState<Batch[]>([]),[batchId,setBatchId]=useState(""),[lots,setLots]=useState<Lot[]>([]),[error,setError]=useState("");
 const [nextPage,setNextPage]=useState(2),[hasMore,setHasMore]=useState(false),[moreBusy,setMoreBusy]=useState(false);
 const [loading,setLoading]=useState(true),lotRequest=useRef(0),selectedBatch=useRef("");
 const loadBatches=useCallback(async()=>{setLoading(true);setError("");try{const d=await requestJson<{batches:Batch[];pagination:{hasNext:boolean}}>("/api/batches"+(initialBatchId?"?batchId="+encodeURIComponent(initialBatchId):""));setBatches(d.batches);setHasMore(d.pagination.hasNext);setNextPage(2);setBatchId(d.batches.find(b=>b.id===initialBatchId)?.id??(d.batches.length===1?d.batches[0].id:""));}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[initialBatchId]);
 useEffect(()=>{let active=true;requestJson<{batches:Batch[];pagination:{hasNext:boolean}}>("/api/batches"+(initialBatchId?"?batchId="+encodeURIComponent(initialBatchId):"")).then(d=>{if(active){setBatches(d.batches);setHasMore(d.pagination.hasNext);setBatchId(d.batches.find(b=>b.id===initialBatchId)?.id??(d.batches.length===1?d.batches[0].id:""));}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[initialBatchId]);
 async function moreBatches(){setMoreBusy(true);try{const d=await requestJson<{batches:Batch[];pagination:{hasNext:boolean}}>("/api/batches?page="+nextPage);setBatches(current=>[...current,...d.batches]);setHasMore(d.pagination.hasNext);setNextPage(current=>current+1);}catch(e){setError((e as Error).message);}finally{setMoreBusy(false);}}
 function chooseBatch(id:string){selectedBatch.current=id;lotRequest.current++;setBatchId(id);setLots([]);setError("");}
 async function refreshLots(id:string){if(selectedBatch.current!==id)return;const sequence=++lotRequest.current;try{const data=await requestJson<{lots:Lot[]}>("/api/lots?batchId="+encodeURIComponent(id));if(sequence===lotRequest.current&&selectedBatch.current===id)setLots(data.lots);}catch(e){if(sequence===lotRequest.current)setError((e as Error).message);}}
 useEffect(()=>{selectedBatch.current=batchId;if(!batchId||!["processor","brand"].includes(role))return;let active=true;const sequence=++lotRequest.current;requestJson<{lots:Lot[]}>("/api/lots?batchId="+encodeURIComponent(batchId)).then(d=>{if(active&&sequence===lotRequest.current)setLots(d.lots);}).catch(e=>{if(active&&sequence===lotRequest.current)setError(e.message);});return()=>{active=false;};},[batchId,role]);
 const select=<SelectField label="Choose your batch" name="batchId" value={batchId} onChange={chooseBatch}><option value="">Select a batch</option>{batches.map(b=><option key={b.id} value={b.id}>{b.breed} · {b.id.slice(0,15)}… · {b.weight} kg</option>)}</SelectField>;
 return <AppShell user={user} role={actualRole}><header className="wt-page-head"><div><p className="wt-eyebrow">YOUR STAGE IN THE JOURNEY</p><h1>{portalDefinitions[role].name}</h1><p>{portalDefinitions[role].description}</p></div><Link className="wt-outline" href={["farmer","buyer"].includes(role)?"/workspace/my-wool":"/dashboard"}>{["farmer","buyer"].includes(role)?"Manage batches":"My overview"} →</Link></header>{error&&<p role="alert" className="wt-error">{error} <button onClick={loadBatches}>Try again</button></p>}
 {actualRole!==role?<section className="wt-card"><h2>This is the {role} workspace.</h2><p>Your selected role is {actualRole}. Change your profile if this is the role you perform. Partner accounts still need the owner’s batch invitation.</p><Link className="wt-button" href="/profile">Update my profile</Link></section>:loading?<section className="wt-card" role="status">Loading your wool…</section>:!batches.length?<section className="wt-card wt-empty"><h2>{role==="farmer"?"Add your first wool batch":"No wool assigned here yet"}</h2><p>{role==="farmer"?"Start a source record before adding the shearing photo.":"The batch owner needs to grant your Google email access for this stage. Check My assignments for other roles or batches."}</p><Link className="wt-button" href={role==="farmer"?"/workspace/my-wool":"/assignments"}>{role==="farmer"?"Register wool":"My assignments"} →</Link></section>:<><section className="wt-card wt-portal-summary"><div className="wt-section-title"><div><h2>{role==="farmer"?"Your source batches":"Wool assigned to you"}</h2><p>{role==="farmer"?"Choose the batch you’re shearing.":"You can record "+portalDefinitions[role].owns.join(", ").toLowerCase()+" for these batches."}</p></div><Link className="wt-outline" href="/assignments">My assignments →</Link></div><div className="wt-portal-assignment-list">{batches.map(b=><button key={b.id} aria-pressed={batchId===b.id} onClick={()=>chooseBatch(b.id)}><strong>{b.breed} wool · {b.weight} kg</strong><small>{b.id.slice(0,18)}…</small></button>)}</div></section><div className="wt-two-columns"><section className="wt-card"><h2>{role==="farmer"?"Complete the shearing record":"Record a stage update"}</h2><p>{role==="farmer"?"Add the actual completion date, final wool weight and a photo.":"Choose a batch assigned to your Google email. Your update becomes public on its QR passport."}</p><ActionForm submit="Save to wool journey" onSubmit={async data=>{
 const payload:Record<string,unknown>={...Object.fromEntries(data),portalRole:role};
 if(role==="farmer"){const file=data.get("photo");if(!(file instanceof File))throw new Error("Choose a shearing photo.");payload.evidenceImageData=await compressPhoto(file);}delete payload.photo;
 await requestJson("/api/batches/events",{method:"POST",body:JSON.stringify(payload)});
 }}>{hasMore&&<button type="button" className="wt-outline" disabled={moreBusy} onClick={moreBatches}>{moreBusy?"Loading…":"Load more assigned batches"}</button>}{select}<SelectField label="Stage" name="title">{actions[role].map(a=><option key={a}>{a}</option>)}</SelectField><div className="wt-fields"><Field name="location" label="Farm, facility or handover location" minLength={2}/>{role!=="farmer"&&<Field name="performedAt" label="Date this stage happened" type="date" max={indiaToday()} value={indiaToday()} help="The actual work date. The time you add it is saved separately."/>}</div>
 {role==="farmer"&&<FormSection title="The completed shearing"><div className="wt-fields"><Field name="shearedAt" label="Shearing completion date" type="date" max={indiaToday()}/><Field name="finalWeightKg" label="Final wool weight" type="number" min=".01" max="100000" step=".01" unit="kg" placeholder="120"/></div><PhotoField/></FormSection>}
 <NotesField placeholder="Weights, conditions, processing details or a report reference."/><label className="wt-check"><input type="checkbox" required/> These details are accurate to the best of my knowledge and may be shown publicly.</label></ActionForm></section>
 <section className="wt-card wt-soft"><h2>Continue the work</h2>{role==="farmer"&&<><Link className="wt-quick-link" href="/workspace/my-wool">Register wool, list a batch or invite partners →</Link><Link className="wt-quick-link" href="/workspace/reverse-bidding">Compare offers and confirm payment →</Link></>}{role==="buyer"&&<Link className="wt-quick-link" href="/workspace/woolkart">Browse wool and place an offer →</Link>}{role==="laboratory"&&<Link className="wt-quick-link" href="/workspace/quality">Record fibre measurements →</Link>}
 {["processor","brand"].includes(role)&&<><h3>Create a traceable output lot</h3><p>Allocate output weight from the source batch or an existing parent lot. The total cannot exceed the parent’s weight.</p><ActionForm disabled={!batchId} submit="Create lot & QR passport" onSubmit={async data=>{await requestJson("/api/lots",{method:"POST",body:JSON.stringify({...Object.fromEntries(data),batchId})});await refreshLots(batchId);}}><p>{batchId?"Selected batch: "+batchId:"Select a batch in the stage form first."}</p><SelectField label="Parent lot" name="parentLotId" required={false}><option value="">Source wool batch</option>{lots.map(l=><option value={l.id} key={l.id}>{l.name} · {l.weightKg} kg</option>)}</SelectField><Field name="name" label="Lot or product name"/><SelectField label="Output type" name="kind">{["clean_wool","yarn","fabric","product"].map(k=><option key={k} value={k}>{k.replaceAll("_"," ")}</option>)}</SelectField><Field name="weightKg" label="Output weight (kg)" type="number" min=".01" max="100000" step=".01"/></ActionForm>{lots.map(l=><Link className="wt-quick-link" key={l.id} href={"/lot/"+l.id}>{l.name} · {l.weightKg} kg · Open QR →</Link>)}</>}
 {batchId&&<Link className="wt-quick-link" href={"/batch/"+batchId}>Open this batch’s public journey →</Link>}<p className="wt-help">These are participant-submitted records, not independent certification. Each update is linked to its account and previous event.</p></section></div></>}</AppShell>;
}
