"use client";
import { useEffect, useRef, useState } from "react";
import AppShell from "@/app/components/app-shell";
import { requestJson } from "@/app/components/forms";
import { insightLocations, type InsightArea } from "@/app/lib/insights-locations";
import type { GoogleUser } from "@/app/lib/google-auth";
type Insights = { location: string; fetchedAt: string; aiEnabled: boolean; weather: { status: string; message: string; sourceUrl?: string; current: { temperatureC: number; humidityPercent: number; windKph: number; precipitationMm: number; observedAt: string } | null; forecast: { date: string; highC: number; lowC: number; rainChancePercent: number | null; rainMm: number }[] }; market: { status: string; source: string; kind: string; period: string; message: string; quotes: { breed: string; grade: string; low: number; high: number; count: number; latest: string }[] } };
export default function InsightsClient({ user, role }: { user: GoogleUser; role: string }) {
  const [area, setArea] = useState<InsightArea>("chitradurga"), [data, setData] = useState<Insights | null>(null), [error, setError] = useState(""), [loading, setLoading] = useState(true), [refresh, setRefresh] = useState(0);
  const [question, setQuestion] = useState(""), [answer, setAnswer] = useState(""), [aiError, setAiError] = useState(""), [aiBusy, setAiBusy] = useState(false), [consent, setConsent] = useState(false);
  const aiVersion = useRef(0);
  useEffect(() => {
    let active = true;
    requestJson<Insights>("/api/insights?area=" + area).then(value => { if (active) { setData(value); setError(""); } }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [area, refresh]);
  async function ask(event: React.FormEvent) {
    event.preventDefault(); if (!consent || aiBusy) return;
    const version = ++aiVersion.current; setAiBusy(true); setAiError(""); setAnswer("");
    try { const result = await requestJson<{ answer: string }>("/api/insights/assistant", { method: "POST", body: JSON.stringify({ area, question, consent: true }) }); if (version === aiVersion.current) setAnswer(result.answer); }
    catch (e) { if (version === aiVersion.current) setAiError((e as Error).message); }
    finally { if (version === aiVersion.current) setAiBusy(false); }
  }
  function changeArea(next: InsightArea) { aiVersion.current++; setArea(next); setData(null); setLoading(true); setError(""); setAnswer(""); setAiError(""); setAiBusy(false); }
  return <AppShell user={user} role={role}><header className="wt-page-head"><div><p className="wt-eyebrow">A LITTLE CONTEXT FOR YOUR NEXT STEP</p><h1>Weather & wool insights</h1><p>Choose an area. Check the sources before you plan a shearing, collection or sale.</p></div></header>
    <section className="wt-card wt-insights-filter"><label>Planning area<select value={area} onChange={e => changeArea(e.target.value as InsightArea)}>{Object.entries(insightLocations).map(([key, value]) => <option key={key} value={key}>{value.name}</option>)}</select></label><button className="wt-outline" disabled={loading} onClick={() => { setLoading(true); setData(null); setRefresh(v => v + 1); }}>Refresh data</button><p className="wt-help">District-centre weather. No device location is requested.</p></section>
    {loading && <p role="status">Checking source data…</p>}{error && <p className="wt-error" role="alert">{error}</p>}
    {data && <><div className="wt-two-columns wt-gap"><section className="wt-card"><p className="wt-eyebrow">NEAR {data.location}</p><h2>Weather for the work ahead</h2>{data.weather.current ? <><div className="wt-insights-metrics"><div><strong>{data.weather.current.temperatureC}°C</strong><small>Temperature</small></div><div><strong>{data.weather.current.humidityPercent}%</strong><small>Humidity</small></div><div><strong>{data.weather.current.windKph} km/h</strong><small>Wind</small></div><div><strong>{data.weather.current.precipitationMm} mm</strong><small>Precipitation</small></div></div><p className="wt-help">Source time: {data.weather.current.observedAt.replace("T", " ")} IST</p><h3>Next three days</h3>{data.weather.forecast.map(day => <div className="wt-forecast-row" key={day.date}><strong>{day.date}</strong><span>{day.lowC}–{day.highC}°C</span><span>Rain: {day.rainChancePercent === null ? "chance unavailable" : day.rainChancePercent + "%"} · {day.rainMm} mm</span></div>)}</> : <p>No live conditions available.</p>}<p className="wt-help">{data.weather.message}</p>{data.weather.sourceUrl && <a className="wt-text-link" href={data.weather.sourceUrl} target="_blank" rel="noreferrer">Source: Open-Meteo ↗</a>}</section>
    <section className="wt-card"><p className="wt-eyebrow">WOOL, NOT CROP PRICES</p><h2>Local seller asking prices</h2><p>{data.market.kind}.</p>{data.market.quotes.length ? data.market.quotes.map(quote => <article className="wt-market-quote" key={quote.breed + quote.grade}><h3>{quote.breed} · {quote.grade}</h3><strong>₹{quote.low.toLocaleString("en-IN")}–₹{quote.high.toLocaleString("en-IN")} / kg</strong><p>{quote.count} listed {quote.count === 1 ? "batch" : "batches"} · Latest batch created {new Date(quote.latest).toLocaleDateString("en-IN", { timeZone: "Asia/Kolkata" })}</p></article>) : <p className="wt-notice">No matching recent wool listings. There isn’t enough data to show an area price.</p>}<p className="wt-help">Source: {data.market.source}. {data.market.period}.</p><p className="wt-help">{data.market.message}</p></section></div>
    <section className="wt-card wt-gap"><p className="wt-eyebrow">HELP MAKING SENSE OF IT</p><h2>Ask the wool assistant</h2><p>Ask about the displayed conditions, price ranges or the next step in your {role} workspace.</p>{!data.aiEnabled ? <p className="wt-notice">AI isn’t enabled yet. The operator needs to add a Gemini API key and model in Vercel. Source data above works separately.</p> : <form className="wt-insights-ai" onSubmit={ask}><label>Your question<textarea value={question} onChange={e => setQuestion(e.target.value)} minLength={5} maxLength={800} required rows={3} placeholder="What should I check before collecting wool in this weather?"/></label><label className="wt-ai-consent"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)}/> Send my question, selected area, active role and displayed source data to Google Gemini. Don’t include private information.</label><button className="wt-button" disabled={aiBusy || !consent} type="submit">{aiBusy ? "Reading the source data…" : "Ask assistant"}</button></form>}{aiError && <p role="alert" className="wt-error">{aiError}</p>}{answer && <div className="wt-ai-answer" role="status"><p>{answer}</p><small>AI-generated guidance—not a live-price source, certificate or guaranteed forecast.</small></div>}</section><p className="wt-help">Page refreshed: {new Date(data.fetchedAt).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST</p></>}
  </AppShell>;
}
