import { ArrowLeft, BadgeCheck, Download, MapPin, QrCode, ShieldCheck, Sprout } from "lucide-react";
import Link from "next/link";

export default async function BatchPassport({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  return <main className="passport-shell">
    <header className="passport-nav"><Link href="/"><span className="brand-mark"><Sprout className="size-4" /></span> WoolTrace</Link><Link href="/dashboard"><ArrowLeft /> Dashboard</Link></header>
    <section className="passport-hero"><div><p className="kicker light">VERIFIED WOOL PASSPORT</p><h1>{id}</h1><p>Kashmir Merino · Grade A · 184 kg</p><span><BadgeCheck /> History verified</span></div><div className="passport-qr"><QrCode /><small>Scan to verify</small></div></section>
    <section className="passport-grid"><article className="passport-main"><div className="passport-heading"><div><p className="kicker">ORIGIN</p><h2>Rafiq Wool Farm</h2><p><MapPin /> Gulmarg, Baramulla, Jammu & Kashmir</p></div><span className="verified-pill"><ShieldCheck /> Verified farmer</span></div><div className="passport-facts"><div><small>Breed</small><strong>Kashmir Merino</strong></div><div><small>Shearing</small><strong>12 Sep 2026</strong></div><div><small>Net weight</small><strong>184 kg</strong></div><div><small>Current owner</small><strong>Rafiq Ahmad</strong></div></div><hr /><p className="kicker">QUALITY ASSESSMENT</p><div className="quality-grid"><div><strong>20.4 μm</strong><span>Fibre diameter</span></div><div><strong>82 mm</strong><span>Staple length</span></div><div><strong>68%</strong><span>Clean yield</span></div><div><strong>A</strong><span>Assigned grade</span></div></div><button className="certificate"><Download /> Download quality certificate</button></article><aside className="passport-side"><p className="kicker">CHAIN OF CUSTODY</p><h2>Farm to fabric</h2>{[["Sheared & registered","Rafiq Wool Farm","12 Sep"],["Quality assessed","Pashmina Lab, Srinagar","13 Sep"],["Listed on WoolKart","Reverse auction opened","14 Sep"],["Transport booked","Himalayan Logistics","16 Sep"]].map(([title,detail,date],i)=><div className={`passport-event ${i<3?"done":""}`} key={title}><span>{i+1}</span><p><strong>{title}</strong><small>{detail}</small></p><time>{date}</time></div>)}</aside></section>
    <footer className="passport-footer"><ShieldCheck /><div><strong>What this record proves</strong><p>This passport links the batch’s origin, quality and custody events. Each update is attached to an authenticated stakeholder account.</p></div></footer>
  </main>;
}
