"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { ArrowRight, Package, QrCode } from "lucide-react";
import AppShell from "@/app/components/app-shell";
import { ActionForm, Field, SelectField, FormSection, requestJson } from "@/app/components/forms";
import { indiaToday } from "@/app/lib/dates";
import type { GoogleUser } from "@/app/lib/google-auth";
type Batch={id:string;breed:string;weight:number;price:number;grade:string;status:string;saleStatus:string;isOwner:boolean;isFarmer:boolean;completedAt:string|null};
type Pagination={page:number;limit:number;total:number;hasNext:boolean};
type Offer={id:string;batchId:string;pricePerKg:number;pickupDays:number;paymentTerms:string;status:string;isSeller:boolean;weightKg:number;paymentReference?:string|null;paidAt?:string|null};
type Booking={id:string;providerName:string;kind:string;scheduledAt:string;status:string};
type Live={location:string;status:string;message?:string;weather:{temperatureC:number;humidityPercent:number;windKph:number;precipitationMm:number;observedAt:string;source:string;sourceUrl:string}|null};
type Payment={qrDataUrl:string;upiUri:string;upiVpa:string;upiName:string;amount:number};
const titles:Record<string,[string,string]>={
 "my-wool":["Your wool, from the beginning.","Register the source, manage listings and connect your supply-chain partners."],
 woolkart:["Good wool. Direct connections.","Explore farmer-listed batches and make your own offer."],
 "reverse-bidding":["Your offers & payments.","Compare prices, agree on a sale and pay the seller directly with UPI."],
 traceability:["Every chapter, one QR.","Open the farmer-recorded origin and the stages added along the way."],
 quality:["Record a measured result.","Only invited laboratory accounts can submit batch measurements."],
 transport:["Plan a collection.","Keep a record of arrangements you make with your transporter."],
 warehouses:["Plan wool storage.","Record your own storage arrangements."],
 services:["A little planning goes a long way.","Save a service plan. Contact the provider yourself to confirm availability."],
 "market-prices":["Market context.","Local conditions for planning shearing and transport. Not a wool-price feed."]
};
function BatchSelect({batches,name="batchId",optional=false}:{batches:Batch[];name?:string;optional?:boolean}){return <SelectField label="Wool batch" name={name} required={!optional} defaultValue=""><option value="">{optional?"No batch linked":"Select a batch"}</option>{batches.map(b=><option key={b.id} value={b.id}>{b.breed} · {b.id.slice(0,15)}… · {b.weight} kg</option>)}</SelectField>;}
export default function WorkspaceClient({module,user,role}:{module:string;user:GoogleUser;role:string}){
 const router=useRouter(),[batches,setBatches]=useState<Batch[]>([]),[offers,setOffers]=useState<Offer[]>([]),[bookings,setBookings]=useState<Booking[]>([]);
 const [error,setError]=useState(""),[loading,setLoading]=useState(true),[payment,setPayment]=useState<Payment|null>(null);
 const [live,setLive]=useState<Live|null>(null);
 const [pagination,setPagination]=useState<Pagination|null>(null),[batchPage,setBatchPage]=useState<Pagination|null>(null),[moreBusy,setMoreBusy]=useState(false);
 const fetchData=useCallback(async():Promise<{batches?:Batch[];bids?:Offer[];bookings?:Booking[];live?:Live;pagination?:Pagination;batchPagination?:Pagination}>=>{
  if(module==="reverse-bidding")return await requestJson<{bids:Offer[]}>("/api/bids");
  if(["services","transport","warehouses"].includes(module)){const [a,b]=await Promise.all([requestJson<{bookings:Booking[]}>("/api/bookings"),requestJson<{batches:Batch[]}>("/api/batches")]);return {...a,...b,pagination:(a as {pagination?:Pagination}).pagination,batchPagination:(b as {pagination?:Pagination}).pagination};}
  if(module==="market-prices")return {live:await requestJson<Live>("/api/live/overview")};
  return await requestJson<{batches:Batch[]}>("/api/batches"+(module==="woolkart"?"?scope=marketplace":""));
 },[module]);
 const apply=useCallback((data:{batches?:Batch[];bids?:Offer[];bookings?:Booking[];live?:Live;pagination?:Pagination;batchPagination?:Pagination})=>{if(data.batches)setBatches(data.batches);if(data.bids)setOffers(data.bids);if(data.bookings)setBookings(data.bookings);if(data.live)setLive(data.live);if(data.pagination)setPagination(data.pagination);if(data.batchPagination)setBatchPage(data.batchPagination);setError("");},[]);
 const load=useCallback(async()=>{setLoading(true);try{apply(await fetchData());}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[fetchData,apply]);
 useEffect(()=>{let active=true;fetchData().then(data=>{if(active)apply(data);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[fetchData,apply]);
 const owned=batches.filter(b=>b.isOwner);
 async function more(batchOnly=false){setMoreBusy(true);try{const info=batchOnly?batchPage:pagination;if(!info?.hasNext)return;const path=batchOnly?"/api/batches":module==="reverse-bidding"?"/api/bids":["services","transport","warehouses"].includes(module)?"/api/bookings":"/api/batches";const query=new URLSearchParams({page:String(info.page+1)});if(module==="woolkart")query.set("scope","marketplace");const data=await requestJson<{batches?:Batch[];bids?:Offer[];bookings?:Booking[];pagination:Pagination}>(path+"?"+query);if(data.batches)setBatches(current=>[...current,...data.batches!]);if(data.bids)setOffers(current=>[...current,...data.bids!]);if(data.bookings)setBookings(current=>[...current,...data.bookings!]);if(batchOnly)setBatchPage(data.pagination);else setPagination(data.pagination);setError("");}catch(e){setError((e as Error).message);}finally{setMoreBusy(false);}}
 async function save(url:string,data:unknown,method="POST"){await requestJson(url,{method,body:JSON.stringify(data)});await load();}
 async function showPayment(id:string){try{setPayment((await requestJson<{payment:Payment}>("/api/payments/upi?bidId="+id)).payment);setError("");}catch(e){setError((e as Error).message);}}
 const [title,description]=module==="my-wool"&&role==="buyer"?["Your purchased wool.","Manage the wool you own and invite partners for its next stage."]:titles[module];
 return <AppShell user={user} role={role}><header className="wt-page-head"><div><p className="wt-eyebrow">WOOLTRACE WORKSPACE</p><h1>{title}</h1><p>{description}</p></div><Link className="wt-outline" href={"/portal/"+role}>My stage portal <ArrowRight size={17}/></Link></header>
 {error&&<p className="wt-error" role="alert">{error} <button onClick={load}>Retry</button></p>}
 {loading&&<p role="status">Loading your records…</p>}
 {module==="my-wool"&&<><div className="wt-two-columns"><section className="wt-card"><h2>{role==="farmer"?"Register a source batch":"Keep your purchases connected"}</h2>{role!=="farmer"?<><p>Purchased batches appear here after the seller confirms your payment. You can then invite laboratories, transporters and processors to add their part of the journey.</p><Link className="wt-button" href="/workspace/woolkart">Find your next batch <ArrowRight size={17}/></Link></>:<ActionForm submit="Start the wool record" success="Batch registered. Open the farmer portal to complete shearing with a photo." onSubmit={async data=>save("/api/batches",Object.fromEntries(data))}><FormSection title="1. Where the wool begins" description="Use the farm or group name you want buyers to see."><div className="wt-fields"><Field name="farmName" label="Farm or farmer group" minLength={2}/><Field name="village" label="Village" minLength={2}/><Field name="district" label="District" minLength={2}/><Field name="state" label="State" value="Karnataka" minLength={2}/></div></FormSection><FormSection title="2. Shearing details" description="Record when shearing begins. Add the final weight and photo from your farmer stage workspace."><div className="wt-fields"><Field name="breed" label="Sheep breed" minLength={2}/><Field name="shearer" label="Shearer or team" minLength={2}/><Field name="date" label="Shearing start date" type="date" max={indiaToday()} help="Today or an earlier date, in India time."/><Field name="weight" label="Expected wool weight" type="number" min=".01" max="100000" step=".01" unit="kg" placeholder="120"/></div></FormSection><FormSection title="3. Your selling preference"><Field name="reserve" label="Minimum price per kg" type="number" min="0" max="1000000" step=".01" unit="₹ / kg" placeholder="90" help="Your batch is listed only after shearing is completed and you choose to list it."/></FormSection><p className="wt-help">Farm details and stage notes appear on the public QR passport. Do not enter private addresses or phone numbers.</p></ActionForm>}</section>
 <section className="wt-card wt-soft"><h2>Connect your partners</h2><p>Use the Google email your partner signs in with. They’ll find this batch in My assignments and open the right workspace. This grants access; no email message is sent.</p><ActionForm submit="Grant batch access" success="Access granted. Ask your partner to sign in with the same Google email and open My assignments." onSubmit={async data=>save("/api/participants",Object.fromEntries(data))}><BatchSelect batches={owned}/><Field name="email" label="Partner’s Google email" type="email"/><SelectField label="Partner role" name="role">{["laboratory","transporter","warehouse","processor","brand"].map(r=><option value={r} key={r}>{r}</option>)}</SelectField></ActionForm><ManageParticipants batches={owned}/></section></div>
 <section className="wt-card wt-gap"><h2>Connected batches</h2>{!loading&&!batches.length&&<p>{role==="farmer"?"No batches yet. Register your first batch above.":"No purchases yet. Browse farmer listings to get started."}</p>}<div className="wt-record-grid">{batches.map(b=><article className="wt-record" key={b.id}><span className="wt-pill">{b.saleStatus}</span><h3>{b.breed} wool</h3><p>{b.weight} kg · {b.status.replaceAll("_"," ")}</p><code>{b.id}</code><Link className="wt-text-link" href={"/batch/"+b.id}><QrCode size={17}/> Public passport</Link>{b.isOwner&&b.isFarmer&&!["accepted","paid","legacy_transferred"].includes(b.saleStatus)&&<ActionForm submit={b.saleStatus==="listed"?"Update listing":"List for offers"} onSubmit={async data=>save("/api/batches",{batchId:b.id,reserve:Number(data.get("reserve")),listed:true},"PATCH")}><Field name="reserve" label="Reserve price (₹/kg)" type="number" value={b.price} min="0" max="1000000" step=".01"/><p className="wt-help">{!b.completedAt?<Link href="/portal/farmer">Complete shearing before listing →</Link>:"Listing makes this batch available for direct offers."}</p></ActionForm>}{b.isOwner&&b.saleStatus==="listed"&&<ActionForm submit="Remove listing" onSubmit={async()=>save("/api/batches",{batchId:b.id,reserve:b.price,listed:false},"PATCH")}>{null}</ActionForm>}</article>)}</div></section></>}
 {module==="woolkart"&&<div className="wt-record-grid">{!loading&&!batches.length&&<section className="wt-card wt-empty"><Package/><h2>No wool listed yet</h2><p>Farmer batches appear here after shearing is complete and the owner lists them.</p></section>}{batches.map(b=><article className="wt-card" key={b.id}><span className="wt-pill">FARMER-LISTED</span><h2>{b.breed} wool</h2><p>{b.weight} kg · Grade {b.grade}</p><h3>₹{b.price.toLocaleString()}<small> / kg reserve</small></h3><Link className="wt-text-link" href={"/batch/"+b.id}>Read the wool passport <ArrowRight size={16}/></Link>{role==="buyer"&&!b.isOwner?<ActionForm submit="Send offer" onSubmit={async data=>save("/api/bids",{...Object.fromEntries(data),batchId:b.id})}><Field name="pricePerKg" label="Your price (₹/kg)" type="number" min={b.price||.01} max="1000000" step=".01"/><Field name="pickupDays" label="Pickup within (days)" type="number" min="0" max="60"/><Field name="paymentTerms" label="Payment terms" placeholder="e.g. UPI before collection"/></ActionForm>:<p className="wt-help">{b.isOwner?"This is your listing.":"Choose the buyer role in your profile to make an offer."}</p>}</article>)}</div>}
 {module==="reverse-bidding"&&<><div className="wt-notice">Payments go directly to the seller. Never share a UPI PIN or OTP. Check the recipient name in your payment app. {role==="farmer"&&<Link href="/profile">Set seller UPI details →</Link>}</div>{payment&&<section className="wt-card wt-payment"><button className="wt-outline" onClick={()=>setPayment(null)}>Close payment details</button><h2>Pay {payment.upiName}</h2><p>₹{payment.amount.toLocaleString("en-IN")} · {payment.upiVpa}</p><Image unoptimized width={260} height={260} src={payment.qrDataUrl} alt="Seller UPI payment QR"/><a className="wt-button" href={payment.upiUri}>Open UPI app</a><p className="wt-help">Scanning does not confirm payment. The seller must check their account. Bank transaction limits may apply.</p></section>}
 <div className="wt-record-grid">{!loading&&!offers.length&&<div className="wt-card wt-empty"><h2>No offers yet</h2><p>{role==="farmer"?"List your completed wool to receive buyer offers.":"Browse farmer listings and submit your first offer."}</p><Link href={role==="farmer"?"/workspace/my-wool":"/workspace/woolkart"} className="wt-button">{role==="farmer"?"Manage my wool":"Browse wool"}</Link></div>}{offers.map(o=><article className="wt-card" key={o.id}><span className="wt-pill">{o.status.replaceAll("_"," ")}</span><h2>₹{o.pricePerKg}/kg</h2><p>{o.weightKg} kg · Pickup in {o.pickupDays} days</p><p>{o.paymentTerms}</p><Link href={"/batch/"+o.batchId} className="wt-text-link">View batch passport <ArrowRight size={16}/></Link>{o.status==="active"&&<ActionForm submit={o.isSeller?"Accept this offer":"Withdraw offer"} onSubmit={async()=>save("/api/bids",{bidId:o.id,action:o.isSeller?"accept":"withdraw"},"PATCH")}>{o.isSeller&&<label className="wt-check"><input type="checkbox" required/> I agree to sell at this price and on these terms.</label>}</ActionForm>}{o.status==="accepted"&&<><button className="wt-outline" onClick={()=>showPayment(o.id)}>Show BHIM / UPI QR</button>{o.isSeller?<ActionForm submit="Confirm receipt & transfer ownership" onSubmit={async data=>save("/api/bids",{bidId:o.id,action:"confirm_payment",reference:data.get("reference")},"PATCH")}><Field name="reference" label="Bank transaction reference"/><label className="wt-check"><input type="checkbox" required/> I checked my bank account and received the full amount. Transfer this batch to the buyer.</label></ActionForm>:<p className="wt-help">Pay the seller and share your transaction reference with them. Ownership changes after their confirmation.</p>}</>}{o.status==="accepted"&&o.isSeller&&<ActionForm submit="Cancel unpaid sale" onSubmit={async()=>save("/api/bids",{bidId:o.id,action:"cancel_sale"},"PATCH")}><label className="wt-check"><input type="checkbox" required/> No payment was received. Cancel this offer and remove the listing.</label></ActionForm>}{o.status==="paid"&&<div className="wt-success">Seller-confirmed payment. Ownership transferred.{o.paymentReference&&<p className="wt-private-reference"><strong>Your payment reference</strong><code>{o.paymentReference}</code><small>Visible only to the seller and winning buyer.</small></p>}</div>}{o.status==="legacy_transferred"&&<p className="wt-help">Historical ownership transfer from the earlier workflow. Bank receipt is not recorded.</p>}</article>)}</div></>}
 {module==="traceability"&&<section className="wt-card wt-narrow"><QrCode size={42}/><h2>Open a wool passport</h2><p>Enter the batch or product-lot ID printed beside the QR. You can also scan its QR with your phone camera.</p><ActionForm submit="View journey" onSubmit={async data=>{const id=String(data.get("id")).trim();if(!/^(WT|LOT)-[A-Za-z0-9-]+$/.test(id))throw new Error("Enter a valid WT- or LOT- identifier.");router.push((id.startsWith("LOT-")?"/lot/":"/batch/")+encodeURIComponent(id));}}><Field name="id" label="Batch or lot ID" placeholder="WT-… or LOT-…"/></ActionForm><Link href="/batch/WT-2610-KAR" className="wt-text-link">View an illustrative example →</Link></section>}
 {module==="quality"&&<section className="wt-card wt-narrow"><h2>Laboratory measurements</h2>{role==="laboratory"?<ActionForm submit="Publish measurements" onSubmit={async data=>save("/api/batches/quality",Object.fromEntries(data))}><BatchSelect batches={batches}/><Field name="grade" label="Assigned grade"/><Field name="micron" label="Fibre diameter (micron)" type="number" min=".01" max="100" step=".01"/><Field name="stapleMm" label="Staple length (mm)" type="number" min=".01" max="500" step=".01"/><Field name="location" label="Laboratory name and location"/></ActionForm>:<p>Your invited laboratory records measurements from its account. <Link href="/labs">Find Karnataka laboratory leads →</Link></p>}</section>}
 {["services","transport","warehouses"].includes(module)&&<div className="wt-two-columns"><section className="wt-card"><h2>Save a service plan</h2><ActionForm submit="Save plan" success="Plan saved. Contact your provider separately to confirm it." onSubmit={async data=>save("/api/bookings",Object.fromEntries(data))}><BatchSelect batches={owned} optional/><SelectField label="Service" name="kind" defaultValue={module==="transport"?"transport":module==="warehouses"?"warehouse":"shearing"}>{["shearing","quality","transport","warehouse","processing","veterinary"].map(k=><option key={k}>{k}</option>)}</SelectField><Field name="providerName" label="Provider you will contact"/><Field name="scheduledAt" label="Planned date" type="date" min={indiaToday()}/></ActionForm></section><section className="wt-card"><h2>Your plans</h2>{!bookings.length&&!loading&&<p>No service plans saved.</p>}{bookings.map(b=><article key={b.id} className="wt-record"><h3>{b.providerName}</h3><p>{b.kind} · {new Date(b.scheduledAt).toLocaleDateString("en-IN")} · {b.status}</p>{b.status!=="cancelled"&&<ActionForm submit="Cancel plan" onSubmit={async()=>save("/api/bookings",{id:b.id},"DELETE")}>{null}</ActionForm>}</article>)}</section></div>}
 {module==="market-prices"&&<section className="wt-card"><h2>No fabricated wool prices</h2><p>WoolTrace does not currently have a licensed live wool-price source. Marketplace offers are actual prices submitted by buyers.</p><Link href="/workspace/woolkart" className="wt-button">See current wool offers</Link>{live&&<div className="wt-gap"><h2>{live.location}</h2>{live.weather?<><div className="wt-metrics"><article><small>Temperature</small><strong>{live.weather.temperatureC}°C</strong></article><article><small>Humidity</small><strong>{live.weather.humidityPercent}%</strong></article><article><small>Rain</small><strong>{live.weather.precipitationMm} mm</strong></article></div><p>Wind: {live.weather.windKph} km/h · Observed {live.weather.observedAt.replace("T"," ")} IST.</p><a className="wt-text-link" href={live.weather.sourceUrl} target="_blank" rel="noreferrer">Weather data by {live.weather.source}</a></>:<p>{live.message}</p>}</div>}</section>}
 {pagination?.hasNext&&<div className="wt-load-more"><p>Showing {module==="reverse-bidding"?offers.length:["services","transport","warehouses"].includes(module)?bookings.length:batches.length} of {pagination.total} records</p><button className="wt-outline" disabled={moreBusy} onClick={()=>more()}>{moreBusy?"Loading…":"Load more records"}</button></div>}{batchPage?.hasNext&&<button className="wt-outline wt-gap" disabled={moreBusy} onClick={()=>more(true)}>Load more batches for your service plan</button>}
 </AppShell>;
}
function ManageParticipants({batches}:{batches:Batch[]}){
 const [selected,setSelected]=useState(""),[records,setRecords]=useState<{id:string;email:string;role:string}[]>([]),[error,setError]=useState("");
 async function load(id:string){setSelected(id);setError("");if(!id){setRecords([]);return;}try{setRecords((await requestJson<{participants:typeof records}>("/api/participants?batchId="+encodeURIComponent(id))).participants);}catch(e){setError((e as Error).message);}}
 return <details className="wt-gap"><summary>Review or remove partner access</summary><SelectField label="Batch" name="reviewBatchId" value={selected} onChange={load}><option value="">Choose a batch</option>{batches.map(b=><option key={b.id} value={b.id}>{b.breed} · {b.id.slice(0,15)}</option>)}</SelectField>{error&&<p role="alert">{error}</p>}{records.map(r=><div key={r.id} className="wt-record"><p>{r.email} · {r.role}</p><ActionForm submit="Remove access" onSubmit={async()=>{await requestJson("/api/participants",{method:"DELETE",body:JSON.stringify({id:r.id,batchId:selected})});await load(selected);}}>{null}</ActionForm></div>)}</details>;
}
