"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, Plus, Package, HandCoins, QrCode, RefreshCw } from "lucide-react";
import AppShell from "@/app/components/app-shell";
import { requestJson } from "@/app/components/forms";
import type { GoogleUser } from "@/app/lib/google-auth";
type Batch={id:string;breed:string;weight:number;status:string;saleStatus:string;bids:number};
export default function DashboardClient({user,role}:{user:GoogleUser;role:string}){
 const [batches,setBatches]=useState<Batch[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 async function load(){try{const data=await requestJson<{batches:Batch[]}>("/api/batches");setBatches(data.batches);setError("");}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{let active=true;requestJson<{batches:Batch[]}>("/api/batches").then(data=>{if(active)setBatches(data.batches);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 return <AppShell user={user}><header className="wt-page-head"><div><p className="wt-eyebrow">YOUR WOOL, CONNECTED</p><h1>Hello, {user.name.split(" ")[0]}.</h1><p>From the first shearing to the final thread. This is your workspace.</p></div><Link className="wt-button" href={role==="farmer"?"/workspace/my-wool":"/portal/"+role}>{role==="farmer"?<Plus size={18}/>:<ArrowRight size={18}/>} {role==="farmer"?"Register wool":"Open my portal"}</Link></header>
 <section className="wt-dashboard-banner"><div><span className="wt-pill">FARMER-RECORDED • QR-LINKED</span><h2>Good wool has a story.<br/>Keep every chapter together.</h2><p>Record the source, invite your partners and let the wool speak for itself.</p><Link href={"/portal/"+role}>Continue your stage <ArrowRight size={18}/></Link></div><div className="wt-banner-art" aria-hidden="true"><QrCode/><span>FARM → FIBRE → FABRIC</span></div></section>
 {error&&<div className="wt-error" role="alert">{error} <button onClick={load}>Retry</button></div>}
 <section className="wt-metrics" aria-busy={loading}>{[[Package,"Connected batches",batches.length],[HandCoins,"Open offers",batches.reduce((sum,b)=>sum+b.bids,0)],[QrCode,"Recorded wool",batches.reduce((sum,b)=>sum+b.weight,0).toLocaleString()+" kg"]].map(([Icon,label,value])=>{const I=Icon as typeof Package;return <article key={String(label)}><I size={22}/><small>{String(label)}</small><strong>{loading?"—":String(value)}</strong></article>;})}</section>
 <div className="wt-two-columns wt-wide-left"><section className="wt-card"><div className="wt-section-title"><div><p className="wt-eyebrow">LATEST ACTIVITY</p><h2>Your wool batches</h2></div><button className="wt-icon-button" aria-label="Refresh batches" disabled={loading} onClick={load}><RefreshCw size={18}/></button></div>{loading?<p role="status">Loading your records…</p>:batches.length?batches.slice(0,5).map(b=><Link className="wt-batch-row" href={"/batch/"+b.id} key={b.id}><span className="wt-batch-icon"><Package/></span><div><strong>{b.breed} wool</strong><small>{b.id.slice(0,15)}… · {b.weight} kg</small></div><span className="wt-pill">{b.status.replaceAll("_"," ")}</span><ArrowRight size={17}/></Link>):<div className="wt-empty"><Package size={38}/><h3>Your first batch starts here</h3><p>{role==="farmer"?"Register the farm source and begin the shearing record.":"Batches appear after a purchase or when an owner invites your Google email."}</p><Link href={role==="farmer"?"/workspace/my-wool":"/workspace/woolkart"} className="wt-button">{role==="farmer"?"Register a batch":"Explore the marketplace"}</Link></div>}<Link className="wt-text-link" href="/workspace/my-wool">View all batches <ArrowRight size={16}/></Link></section>
 <section className="wt-card wt-soft"><p className="wt-eyebrow">A SIMPLE NEXT STEP</p><h2>Make the journey visible.</h2><ol className="wt-steps"><li>Add the farm and shearing details.</li><li>Complete shearing with a photo.</li><li>List wool and compare buyer offers.</li><li>Invite partners to add their stage.</li></ol><Link className="wt-text-link" href="/workspace/traceability">Open a wool passport <ArrowRight size={16}/></Link><p className="wt-help">All figures above come from your database records. No sample sales or simulated market prices.</p></section></div></AppShell>;
}
